freebsd_task:
    timeout_in: 120m
    install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f && pkg install -y bash iperf3 wireguard-tools
    build_script:
    - make -j $(sysctl -n hw.ncpu) -C src DEBUG_FLAGS=-DSELFTESTS
    test_script:
    - kldload src/if_wg.ko
    - tests/netns.sh
    matrix:
    - name: freebsd12-1-amd64
      freebsd_instance:
        image: freebsd-12-1-release-amd64
    - name: freebsd12-2-amd64
      freebsd_instance:
        image: freebsd-12-2-release-amd64
    - name: freebsd12-3-amd64
      freebsd_instance:
        image: freebsd-12-3-release-amd64
    - name: freebsd13-0-amd64
      freebsd_instance:
        image: freebsd-13-0-release-amd64
    - name: freebsd13-1-amd64
      freebsd_instance:
        image: freebsd-13-1-release-amd64
